import { useEffect, useState } from 'react';
import { AlertTriangle } from 'lucide-react';
import { Checkbox } from "@/components/ui/checkbox";
import { hasAcceptedDisclaimer, saveDisclaimerAcceptance } from "@/lib/utils";

interface DisclaimerModalProps {
  onAccept: () => void;
}

export default function DisclaimerModal({ onAccept }: DisclaimerModalProps) {
  const [open, setOpen] = useState(false);
  const [doNotShow, setDoNotShow] = useState(false);

  useEffect(() => {
    // Check if the user has already accepted the disclaimer
    if (!hasAcceptedDisclaimer()) {
      setOpen(true);
    }
  }, []);

  const handleAccept = () => {
    if (doNotShow) {
      saveDisclaimerAcceptance();
    }
    setOpen(false);
    onAccept();
  };

  const showFullDisclaimer = () => {
    alert("Drama Llama is an AI-powered communication analysis tool designed for educational and informational purposes only. The analysis and insights provided are generated by artificial intelligence and should not be interpreted as professional advice, therapy, clinical diagnosis, or legal guidance. Users should exercise their own judgment and consult qualified professionals for serious matters related to communication, relationships, or mental health concerns.");
  };

  if (!open) return null;

  return (
    <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-xl max-w-md w-full p-6 shadow-xl">
        <div className="flex flex-col items-center text-center">
          <div className="flex items-center mb-3">
            <AlertTriangle className="h-6 w-6 text-amber-500 mr-2" />
            <h2 className="text-2xl font-bold text-pink-500">Welcome to Drama Llama</h2>
          </div>
          
          <p className="text-gray-700 text-lg mb-4">Before you begin, please note:</p>
          
          <p className="text-gray-700 mb-6">
            Drama Llama provides AI-generated insights and is not intended for clinical, legal, or 
            diagnostic use. For full context, please review our disclaimer.
          </p>
          
          <button 
            className="text-pink-500 font-medium mb-6 hover:underline"
            onClick={showFullDisclaimer}
          >
            Click here to read the full disclaimer
          </button>
          
          <div className="flex items-center mb-6">
            <Checkbox 
              id="do-not-show" 
              checked={doNotShow}
              onCheckedChange={(checked) => setDoNotShow(checked as boolean)}
            />
            <label 
              htmlFor="do-not-show" 
              className="ml-2 text-sm text-gray-700 cursor-pointer"
            >
              Do not show this again
            </label>
          </div>
          
          <button
            onClick={handleAccept}
            className="w-full py-3 px-4 rounded-full font-medium text-white bg-gradient-to-r from-pink-500 to-teal-400 hover:opacity-90 transition-opacity"
          >
            I Understand & Approve
          </button>
        </div>
      </div>
    </div>
  );
}